#!/usr/bin/env bash
# Script that installs nginx and configures a custom HTTP response header

apt-get update -y
apt-get install -y nginx

# Get the hostname of the server
HOSTNAME=$(hostname)

# Insert custom header into nginx config
sed -i "/server_name _;/a \    add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default

# Restart nginx to apply changes
service nginx restart
