#!/usr/bin/env bash
# Script that installs nginx and configures a custom HTTP response header

apt-get update -y
apt-get install -y nginx

# Insert custom header into nginx config
sed -i '/server_name _;/a \    add_header X-Served-By $hostname;' /etc/nginx/sites-available/default

# Restart nginx
service nginx restart
